# Generated by Django 3.2.3 on 2021-11-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_imageload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageload',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Файл'),
        ),
    ]
