# Generated by Django 3.2.3 on 2021-11-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_imageload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageload',
            name='image_link',
        ),
    ]
